export const mockBookings = [
  {
    id: 1,
    booking_id: "BK-001",
    guest_name: "John Doe",
    agent_name: "Airbnb",
    platform: "Airbnb",
    check_in: "2026-01-15",
    check_out: "2026-01-18",
    nights: 3,
    amount: 24000,
    payment_status: "Paid",
    stay_status: "Upcoming",
    notes: "Late check-in",
  },
  {
    id: 2,
    booking_id: "BK-002",
    guest_name: "Mary Wanjiku",
    agent_name: "Booking.com",
    platform: "Booking.com",
    check_in: "2026-01-10",
    check_out: "2026-01-14",
    nights: 4,
    amount: 32000,
    payment_status: "Unpaid",
    stay_status: "Ongoing",
    notes: "",
  },
];
