# Generated by Django 6.0.1 on 2026-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('Airbnb', 'Airbnb'), ('Booking.com', 'Booking.com'), ('Agent', 'Agent'), ('Direct', 'Direct'), ('Other', 'Other')], default='Airbnb', max_length=20)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('house', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], default='Unpaid', max_length=10)),
                ('stay_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('studio', 'Studio'), ('1bed', 'One Bedroom')], max_length=10)),
                ('max_occupancy', models.IntegerField(default=2)),
            ],
        ),
    ]
