# Generated by Django 6.0.1 on 2026-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0003_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='house',
            field=models.CharField(choices=[('B1-3', 'B1-3 (Studio)'), ('B2-8', 'B2-8 (Studio)'), ('B3-10', 'B3-10 (Studio)'), ('B7-7', 'B7-7 (Studio)'), ('A4', 'A4 (1 Bedroom)'), ('A5', 'A5 (1 Bedroom)'), ('G3', 'G3 (1 Bedroom)'), ('1B', '1B (1 Bedroom)')], default='B1-3', max_length=20),
        ),
    ]
