# Generated by Django 6.0.1 on 2026-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0005_alter_booking_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
