# Generated by Django 6.0.1 on 2026-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0006_booking_amount_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount_today',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
