# Generated by Django 6.0.1 on 2026-03-10 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0008_alter_booking_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
