# Generated by Django 6.0.1 on 2026-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0009_booking_amount_paid_booking_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_date',
            new_name='last_payment_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=10),
        ),
    ]
