# Generated by Django 6.0.1 on 2026-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0010_rename_payment_date_booking_last_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_payment_date',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
    ]
