# Generated by Django 6.0.1 on 2026-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0013_alter_booking_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
