# Generated by Django 6.0.1 on 2026-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbapp', '0014_room_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='house',
            field=models.CharField(choices=[('B1-3', 'B1-3'), ('B2-7', 'B2-7'), ('B3-10', 'B3-10'), ('B5-6', 'B5-6'), ('B7-7', 'B7-7'), ('A4', 'A4'), ('1B', '1B')], default='B1-3', max_length=20),
        ),
    ]
